# -*- coding: utf-8 -*-
"""analysis_on_global_coffee_consumption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYhQkh47OUQGKo8eNMJxKThABVyuXJoM
"""

import pandas as pd
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/Robinlovelace/geocompr/master/extdata/coffee-data.csv"
df = pd.read_csv(url)

filename = "coffee_consumption.csv"
df.to_csv(filename, index=False)

df_clean = df[['name_long', target_col]].copy()
df_clean = df_clean.rename(columns={'name_long': 'Country', target_col: 'Consumption_KG'})
df_clean = df_clean.dropna()
if df_clean['Consumption_KG'].dtype == object:
    df_clean['Consumption_KG'] = df_clean['Consumption_KG'].astype(str).str.replace(',', '')
df_clean['Consumption_KG'] = pd.to_numeric(df_clean['Consumption_KG'])
df_clean['Estimated_Cups'] = df_clean['Consumption_KG'] * 100
df_clean['Estimated_Cups_Billions'] = df_clean['Estimated_Cups'] / 1_000_000_000

plt.figure(figsize=(12, 7))
bars = plt.barh(df_top['Country'], df_top['Estimated_Cups_Billions'], color='#4B3621') # Coffee brown color
plt.title('Top 10 Countries by Total Coffee Consumption', fontsize=15)
plt.xlabel('Estimated Consumption (Billions of Cups)', fontsize=12)
plt.ylabel('Country', fontsize=12)
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()